# cloudbuild.yaml
steps:
  - name: gcr.io/$PROJECT_ID/cloudbuild-android
    id: 'copy-persistent'
    args: ['cp', '-a', '.', '/persistent_volume']
    volumes:
      - name: data
        path: /persistent_volume

  # Static code analysis by SonarQube.
  # TODO(eric): Change sonarqube URL to https when the certificate is available.
  - name: gcr.io/cloud-builders/docker
    id: 'sonarqube-analysis'
    volumes:
      - name: data
        path: /persistent_volume
    args: ['run', '-v', 'data:/workspace', '--rm', 'gcr.io/$PROJECT_ID/cloudbuild', '/bin/sh', '-c',\
           'cd /workspace && ./gradlew clean sonarqube '\
           '-Dsonar.host.url=http://sonarqube.nextsense.io/ '\
           '-Dsonar.login=1bcdb5a82cd7ef74fbbf0bb46ede682e085e89b9'
    ]

  - name: gcr.io/cloud-builders/docker
    id: 'gradle-build'
    volumes:
      - name: data
        path: /persistent_volume
    args: ['run', '-v', 'data:/workspace', '--rm', 'gcr.io/$PROJECT_ID/cloudbuild', '/bin/sh', '-c',\
           'cd /workspace && ./gradlew app:assembleDebug && mv app/build/outputs/apk/debug/app-debug.aar app/build/outputs/apk/debug/$REPO_NAME-$SHORT_SHA-debug.aar && ls -la app/build/outputs/apk/debug/$REPO_NAME-$SHORT_SHA-debug.aar']

  - name: gcr.io/cloud-builders/gsutil
    id: 'publish-gsutil'
    args: ['cp',\
           '/persistent_volume/app/build/outputs/aar/debug/$REPO_NAME-$SHORT_SHA-debug.aar',\
           'gs://artifacts.$PROJECT_ID.appspot.com/android/']
    volumes:
      - name: data
        path: /persistent_volume

timeout: 1200s