# cloudbuild.yaml
# TODO(eric): Save the build cache to speed up.
steps:
  # Copy all the source files to the cloud build persistent volume.
  - name: gcr.io/$PROJECT_ID/cloudbuild-android
    id: 'copy-persistent'
    args: ['cp', '-a', '.', '/persistent_volume']
    volumes:
      - name: data
        path: /persistent_volume

  # Static code analysis by SonarQube.
  # TODO(eric): Change sonarqube URL to https when the certificate is available.
  - name: gcr.io/cloud-builders/docker
    id: 'sonarqube-analysis'
    volumes:
      - name: data
        path: /persistent_volume
    args: ['run', '-v', 'data:/workspace', '--rm', 'gcr.io/$PROJECT_ID/cloudbuild-android', '/bin/sh', '-c', 'cd /workspace && ./gradlew clean sonarqube -Dsonar.host.url=http://sonarqube.nextsense.io/ -Dsonar.login=8eda7d8b0d87bda142a80e22877b078e7a215a62'
    ]

  # Build the library.
  # TODO(eric): Add a parameter for the trigger to configure the name for releases? Or maybe the
  # artifact registry can take care of that.
  - name: gcr.io/cloud-builders/docker
    id: 'gradle-build'
    volumes:
      - name: data
        path: /persistent_volume
    args: ['run', '-v', 'data:/workspace', '--rm', 'gcr.io/$PROJECT_ID/cloudbuild-android', '/bin/sh', '-c', 'cd /workspace && ./gradlew app:assembleDebug && mv app/build/outputs/aar/app-debug.aar app/build/outputs/aar/$REPO_NAME-$SHORT_SHA-debug.aar && ls -la app/build/outputs/aar/$REPO_NAME-$SHORT_SHA-debug.aar']

  # TODO(eric): Copy to the artifact registry instead?
  # Copy the built library to cloud storage.
  - name: gcr.io/cloud-builders/gsutil
    id: 'publish-gsutil'
    args: ['cp', '/persistent_volume/app/build/outputs/aar/$REPO_NAME-$SHORT_SHA-debug.aar', 'gs://artifacts.$PROJECT_ID.appspot.com/android/']
    volumes:
      - name: data
        path: /persistent_volume

timeout: 1200s
