import 'package:nextsense_trial_ui/domain/firebase_entity.dart';

enum EventContext {
  protocol,  // Event generated by a protocol.
}

/// Each entry corresponds to a field name in the database instance.
enum EventKey {
  // Event type id.
  type,
  // Event type abbreviation. Need to keep for now as the back-end need this field to create the
  // CSV for the old internal dashboard.
  marker,
  // When the event started as a GMT timestamp.
  start_datetime,
  // When the event finished as a GMT timestamp.
  end_datetime,
  // Context of how the event was generated. See [EventContext].
  context
}

class Event extends FirebaseEntity<EventKey> {

  Event(FirebaseEntity firebaseEntity) : super(firebaseEntity.getDocumentSnapshot());
}