name: flutter_common
description: Common Flutter Library
version: 0.0.1
publish_to: none
homepage: nextsense.io

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0 <4.0.0" # Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  nextsense_base:
    path: ../nextsense_base
  cloud_firestore: ^4.3.1
  community_charts_flutter: ^1.0.1
  device_info_plus: ^9.0.0
  email_validator: ^2.1.16
  firebase_app_check: ^0.1.1+12
  firebase_auth: ^4.10.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter_hooks: ^0.18.2+1
  get_it: ^7.6.4
  google_sign_in: ^5.1.0
  http: ^1.1.0
  iirjdart: ^0.1.0
  intl: ^0.18.0
  logging: ^1.0.2
  path_provider: ^2.0.8
  permission_handler: ^10.4.5
  scidart: ^0.0.2-dev.9
  shared_preferences: ^2.0.13
  stacked: ^3.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        default_package: io.nextsense.main.flutter.common

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
